// Sharing and Export Features for Sonnet Generator
// Comprehensive sharing, export, and social media functionality

console.log('Sharing features loaded - Phase 4 implementation');

// ===============================
// SHARING AND EXPORT FUNCTIONS
// ===============================

// Enhanced copy to clipboard with rich formatting
async function copyFormattedSonnet(sonnet, format = 'rich') {
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('copyFormattedSonnet: Invalid sonnet object or lines array');
        alert('Cannot copy: No sonnet content available');
        return false;
    }
    
    try {
        let textContent = '';
        let htmlContent = '';
        
        const title = document.getElementById('sonnet-title')?.textContent || 'Untitled Sonnet';
        const theme = (sonnet.theme || 'unknown').charAt(0).toUpperCase() + (sonnet.theme || 'unknown').slice(1);
        const mood = (sonnet.mood || 'unknown').charAt(0).toUpperCase() + (sonnet.mood || 'unknown').slice(1);
        
        // Safely validate and filter lines
        const validLines = sonnet.lines.filter(line => line && line.trim());
        if (validLines.length === 0) {
            console.error('copyFormattedSonnet: No valid content in sonnet lines');
            alert('Cannot copy: No sonnet content available');
            return false;
        }
        
        if (format === 'rich') {
            // Rich text format for applications that support it
            textContent = `${title}\n\n${validLines.join('\n')}\n\n--- \nGenerated by Sonnet Generator\nTheme: ${theme} | Mood: ${mood}`;
            
            htmlContent = `
                <div style="font-family: 'Crimson Text', serif; line-height: 1.6; max-width: 500px;">
                    <h3 style="color: #1a365d; margin-bottom: 1rem; font-style: italic;">${title}</h3>
                    <div style="margin-bottom: 1rem;">
                        ${validLines.map(line => `<p style="margin: 0.5rem 0;">${line}</p>`).join('')}
                    </div>
                    <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 1rem 0;">
                    <p style="font-size: 0.9rem; color: #718096; margin: 0;">
                        Generated by Sonnet Generator<br>
                        Theme: ${theme} | Mood: ${mood}
                    </p>
                </div>
            `;
        } else if (format === 'social') {
            // Optimized for social media
            const firstLine = validLines[0] || 'Generated sonnet';
            textContent = `"${firstLine}..."\n\n${title}\nGenerated with Sonnet Generator 📝✨\n\n#poetry #sonnet #creative #writing`;
        } else {
            // Plain text format
            textContent = `${title}\n\n${validLines.join('\n')}\n\n- Generated by Sonnet Generator`;
        }
        
        // Try to copy both plain text and HTML
        if (navigator.clipboard && window.ClipboardItem) {
            const clipboardItem = new ClipboardItem({
                'text/plain': new Blob([textContent], { type: 'text/plain' }),
                'text/html': new Blob([htmlContent], { type: 'text/html' })
            });
            await navigator.clipboard.write([clipboardItem]);
        } else if (navigator.clipboard) {
            await navigator.clipboard.writeText(textContent);
        } else {
            // Fallback for older browsers
            fallbackCopyToClipboard(textContent);
        }
        
        showCopySuccess(format);
        return true;
        
    } catch (error) {
        console.error('Failed to copy formatted sonnet:', error);
        showCopyError();
        return false;
    }
}

// Social media sharing functions
function shareToTwitter() {
    const sonnet = window.currentSonnet;
    console.log('Attempting to share to Twitter with sonnet:', sonnet);
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('shareToTwitter: Invalid sonnet object or lines array');
        alert('Cannot share: No sonnet content available');
        return;
    }
    
    const title = document.getElementById('sonnet-title')?.textContent || 'My Sonnet';
    const firstLine = sonnet.lines[0] || '';
    const lastLine = sonnet.lines[sonnet.lines.length - 1] || '';
    
    if (!firstLine && !lastLine) {
        console.error('shareToTwitter: No content in sonnet lines');
        alert('Cannot share: No sonnet content available');
        return;
    }
    
    const text = `"${firstLine}...${lastLine}"\n\n${title} - Generated with Sonnet Generator ✨\n\n#poetry #sonnet #creative #writing`;
    const url = encodeURIComponent(window.location.href);
    const tweetText = encodeURIComponent(text);
    
    const twitterUrl = `https://twitter.com/intent/tweet?text=${tweetText}&url=${url}`;
    window.open(twitterUrl, '_blank', 'width=550,height=420');
}

function shareToFacebook() {
    const sonnet = window.currentSonnet;
    console.log('Attempting to share to Facebook with sonnet:', sonnet);
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('shareToFacebook: Invalid sonnet object or lines array');
        alert('Cannot share: No sonnet content available');
        return;
    }
    
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(document.getElementById('sonnet-title')?.textContent || 'My Sonnet');
    const firstLine = sonnet.lines[0] || 'Generated sonnet';
    const description = encodeURIComponent(`Check out this beautiful sonnet I generated: "${firstLine}..."`);
    
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${url}&title=${title}&description=${description}`;
    window.open(facebookUrl, '_blank', 'width=626,height=436');
}

function shareToPinterest(sonnet) {
    // Generate an image URL (placeholder - would need image generation)
    const imageUrl = encodeURIComponent(generateSonnetImageUrl(sonnet));
    const url = encodeURIComponent(window.location.href);
    const description = encodeURIComponent(`Beautiful sonnet: ${document.getElementById('sonnet-title')?.textContent || 'My Sonnet'}`);
    
    const pinterestUrl = `https://www.pinterest.com/pin/create/button/?url=${url}&media=${imageUrl}&description=${description}`;
    window.open(pinterestUrl, '_blank', 'width=750,height=320');
}

function shareViaEmail(sonnet) {
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('shareViaEmail: Invalid sonnet object or lines array');
        alert('Cannot share: No sonnet content available');
        return;
    }
    
    const title = document.getElementById('sonnet-title')?.textContent || 'My Sonnet';
    const subject = encodeURIComponent(`Beautiful Sonnet: ${title}`);
    
    // Safely join the lines with validation
    const sonnetText = sonnet.lines.filter(line => line && line.trim()).join('\n');
    
    if (!sonnetText) {
        console.error('shareViaEmail: No valid content in sonnet lines');
        alert('Cannot share: No sonnet content available');
        return;
    }
    
    const body = encodeURIComponent(
        `I wanted to share this beautiful sonnet I generated:\n\n` +
        `${title}\n\n` +
        `${sonnetText}\n\n` +
        `Generated using the Sonnet Generator at ${window.location.href}\n\n` +
        `Hope you enjoy it!`
    );
    
    const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;
    window.location.href = mailtoUrl;
}

// Advanced download options
function downloadAsText(sonnet, includeMetadata = true) {
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('downloadAsText: Invalid sonnet object or lines array');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    const title = document.getElementById('sonnet-title')?.textContent || 'Untitled Sonnet';
    let content = `${title}\n${'='.repeat(title.length)}\n\n`;
    
    // Safely join lines with validation
    const validLines = sonnet.lines.filter(line => line && line.trim());
    if (validLines.length === 0) {
        console.error('downloadAsText: No valid content in sonnet lines');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    content += validLines.join('\n');
    
    if (includeMetadata) {
        content += '\n\n' + '─'.repeat(30) + '\n';
        content += `Theme: ${(sonnet.theme || 'unknown').charAt(0).toUpperCase() + (sonnet.theme || 'unknown').slice(1)}\n`;
        content += `Mood: ${(sonnet.mood || 'unknown').charAt(0).toUpperCase() + (sonnet.mood || 'unknown').slice(1)}\n`;
        content += `Type: ${(sonnet.sonnetType || 'unknown').charAt(0).toUpperCase() + (sonnet.sonnetType || 'unknown').slice(1)}\n`;
        content += `Rhyme Scheme: ${sonnet.rhymeScheme && Array.isArray(sonnet.rhymeScheme) ? sonnet.rhymeScheme.join(' ') : 'N/A'}\n`;
        content += `Generated: ${new Date().toLocaleDateString()}\n`;
        content += `Quality Score: ${sonnet.quality && sonnet.quality.overall ? Math.round(sonnet.quality.overall * 100) : 'N/A'}%\n`;
        content += '\nGenerated by Sonnet Generator\n';
    }
    
    downloadTextFile(content, `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.txt`);
}

function downloadAsPDF(sonnet) {
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('downloadAsPDF: Invalid sonnet object or lines array');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    // Note: This would require a PDF library like jsPDF
    // For now, we'll create a print-optimized HTML version
    const title = document.getElementById('sonnet-title')?.textContent || 'Untitled Sonnet';
    
    // Safely validate and filter lines
    const validLines = sonnet.lines.filter(line => line && line.trim());
    if (validLines.length === 0) {
        console.error('downloadAsPDF: No valid content in sonnet lines');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>${title}</title>
            <style>
                @page { margin: 2cm; }
                body { 
                    font-family: 'Crimson Text', serif; 
                    line-height: 1.8; 
                    color: #2d3748;
                    max-width: 600px;
                    margin: 0 auto;
                }
                .sonnet-title { 
                    text-align: center; 
                    font-size: 24px; 
                    margin-bottom: 30px;
                    color: #1a365d;
                    font-style: italic;
                }
                .sonnet-line { 
                    margin-bottom: 12px; 
                    font-size: 16px;
                    text-align: center;
                }
                .metadata { 
                    margin-top: 40px; 
                    padding-top: 20px; 
                    border-top: 1px solid #e2e8f0;
                    font-size: 12px;
                    color: #718096;
                    text-align: center;
                }
            </style>
        </head>
        <body>
            <h1 class="sonnet-title">${title}</h1>
            ${validLines.map(line => `<div class="sonnet-line">${line}</div>`).join('')}
            <div class="metadata">
                <p>Theme: ${sonnet.theme || 'Unknown'} | Mood: ${sonnet.mood || 'Unknown'} | Type: ${sonnet.sonnetType || 'Unknown'}</p>
                <p>Generated by Sonnet Generator on ${new Date().toLocaleDateString()}</p>
            </div>
        </body>
        </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function downloadAsImage(sonnet) {
    if (!sonnet || !sonnet.lines || !Array.isArray(sonnet.lines) || sonnet.lines.length === 0) {
        console.error('downloadAsImage: Invalid sonnet object or lines array');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    // Create a canvas to generate the image
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    
    // Set canvas size
    canvas.width = 800;
    canvas.height = 1000;
    
    // Background
    ctx.fillStyle = '#faf7f0';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    
    // Add subtle border
    ctx.strokeStyle = '#d4af37';
    ctx.lineWidth = 3;
    ctx.strokeRect(50, 50, canvas.width - 100, canvas.height - 100);
    
    // Title
    ctx.font = 'italic 32px serif';
    ctx.fillStyle = '#1a365d';
    ctx.textAlign = 'center';
    const title = document.getElementById('sonnet-title')?.textContent || 'Untitled Sonnet';
    ctx.fillText(title, canvas.width / 2, 140);
    
    // Safely validate and filter lines
    const validLines = sonnet.lines.filter(line => line && line.trim());
    if (validLines.length === 0) {
        console.error('downloadAsImage: No valid content in sonnet lines');
        alert('Cannot download: No sonnet content available');
        return;
    }
    
    // Sonnet lines
    ctx.font = '22px serif';
    ctx.fillStyle = '#2d3748';
    let y = 200;
    
    validLines.forEach((line, index) => {
        ctx.fillText(line, canvas.width / 2, y);
        y += 40;
    });
    
    // Metadata
    ctx.font = '16px sans-serif';
    ctx.fillStyle = '#718096';
    y += 40;
    ctx.fillText(`${sonnet.theme} • ${sonnet.mood} • ${sonnet.sonnetType}`, canvas.width / 2, y);
    
    // Attribution
    y += 30;
    ctx.fillText('Generated by Sonnet Generator', canvas.width / 2, y);
    
    // Download the image
    canvas.toBlob(blob => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }, 'image/png');
}

// Utility functions
function downloadTextFile(content, filename) {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

function generateSonnetImageUrl(sonnet) {
    // Placeholder function - in a real implementation, this would generate
    // a proper image URL or use a service like Canvas API
    // Generate a placeholder image URL or use a data URI
    return "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjMWEzNjVkIi8+Cjx0ZXh0IHg9IjI1MCIgeT0iMjUwIiBmb250LWZhbWlseT0iQ3JpbXNvbiBUZXh0LCBzZXJpZiIgZm9udC1zaXplPSIzMiIgZmlsbD0iI2Y3ZmFmYyIgdGV4dC1hbmNob3I9Im1pZGRsZSI+U29ubmV0PC90ZXh0Pgo8L3N2Zz4=";
}

// UI feedback functions
function showCopySuccess(format) {
    const formatNames = {
        'rich': 'Rich Text',
        'social': 'Social Media',
        'plain': 'Plain Text'
    };
    
    const message = document.createElement('div');
    message.className = 'copy-notification success';
    message.innerHTML = `
        <span class="notification-icon">📋</span>
        <span class="notification-text">Copied as ${formatNames[format] || 'Text'}!</span>
    `;
    
    document.body.appendChild(message);
    setTimeout(() => {
        message.classList.add('fade-out');
        setTimeout(() => document.body.removeChild(message), 300);
    }, 2000);
}

function showCopyError() {
    const message = document.createElement('div');
    message.className = 'copy-notification error';
    message.innerHTML = `
        <span class="notification-icon">❌</span>
        <span class="notification-text">Copy failed. Please try again.</span>
    `;
    
    document.body.appendChild(message);
    setTimeout(() => {
        message.classList.add('fade-out');
        setTimeout(() => document.body.removeChild(message), 300);
    }, 3000);
}

// Enhanced sharing menu
function showSharingMenu(sonnet) {
    const menu = document.createElement('div');
    menu.className = 'sharing-menu';
    menu.innerHTML = `
        <div class="sharing-menu-content">
            <h4>Share Your Sonnet</h4>
            <div class="sharing-options">
                <button class="sharing-option" onclick="shareToTwitter(currentSonnet)">
                    <span class="option-icon">🐦</span>
                    <span class="option-text">Twitter</span>
                </button>
                <button class="sharing-option" onclick="shareToFacebook(currentSonnet)">
                    <span class="option-icon">📘</span>
                    <span class="option-text">Facebook</span>
                </button>
                <button class="sharing-option" onclick="shareToPinterest(currentSonnet)">
                    <span class="option-icon">📌</span>
                    <span class="option-text">Pinterest</span>
                </button>
                <button class="sharing-option" onclick="shareViaEmail(currentSonnet)">
                    <span class="option-icon">✉️</span>
                    <span class="option-text">Email</span>
                </button>
            </div>
            <div class="copy-options">
                <h5>Copy Options</h5>
                <button class="copy-option" onclick="copyFormattedSonnet(currentSonnet, 'rich')">Rich Text</button>
                <button class="copy-option" onclick="copyFormattedSonnet(currentSonnet, 'social')">Social Media</button>
                <button class="copy-option" onclick="copyFormattedSonnet(currentSonnet, 'plain')">Plain Text</button>
            </div>
            <div class="download-options">
                <h5>Download Options</h5>
                <button class="download-option" onclick="downloadAsText(currentSonnet)">Text File</button>
                <button class="download-option" onclick="downloadAsPDF(currentSonnet)">PDF</button>
                <button class="download-option" onclick="downloadAsImage(currentSonnet)">Image</button>
            </div>
            <button class="close-menu" onclick="closeSharingMenu()">Close</button>
        </div>
        <div class="sharing-menu-overlay" onclick="closeSharingMenu()"></div>
    `;
    
    document.body.appendChild(menu);
    window.currentSonnet = sonnet; // Store for button callbacks
}

function closeSharingMenu() {
    const menu = document.querySelector('.sharing-menu');
    if (menu) {
        document.body.removeChild(menu);
    }
}

// Export all sharing functions
window.SharingFeatures = {
    copyFormattedSonnet,
    shareToPinterest,
    shareViaEmail,
    downloadAsText,
    downloadAsPDF,
    downloadAsImage,
    showSharingMenu,
    closeSharingMenu
};

